### ISSUE TITLE
Fixing the issues that did not allow to pass on Workflow/Actions

### ISSUE THREAD

**Issue by d-yerovi** [d-yerovi/user_management#4]
Here is the list of things that needed to change to allow code to load and pass Action test.

1. Update the Docker credentials with my User/Token and repository

```
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dyerovi/user_management:${{ github.sha }} # Uses the Git SHA for tagging | update with my credentials 
          platforms: linux/amd64,linux/arm64 # Multi-platform support
          cache-from: type=registry,ref=dyerovi/user_management:cache # update with my credentials
          cache-to: type=inline,mode=max
          
      - name: Scan the Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dyerovi/user_management:${{ github.sha }}' # update with my credentials
          format: 'table'
          exit-code: '1' # Fail the job if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
```

2. Make a few modification on Dockerfile to fix "build-and-push-docker"
[Updating dockerfile to fix 100 error message on Actions](https://github.com/d-yerovi/user_management/pull/2)

```
[build-and-push-docker](https://github.com/d-yerovi/user_management/actions/runs/10136601916/job/28025651518#step:6:401)
buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y libc-bin=2.36-9+deb12u6     && apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
```

3. Make a few modification on requirements.txt to fix "build-and-push-docker" error at the moment to build image - [updating version in requirements.txt with PyMySQL==1.1.1](https://github.com/d-yerovi/user_management/pull/3/files) 

```
Python (python-pkg)
===================
Total: 1 (HIGH: 0, CRITICAL: 1)

┌────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│      Library       │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                           │
├────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────────┤
│ PyMySQL (METADATA) │ CVE-2024-36039 │ CRITICAL │ fixed  │ 1.1.0             │ 1.1.1         │ python-pymysql: SQL injection if used with untrusted JSON │
│                    │                │          │        │                   │               │ input                                                     │
│                    │                │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2024-36039                │
└────────────────────┴────────────────┴──────────┴────────┴───────────────────┴────────
```
